In [1]:
import pandas as pd
df = pd.read_csv('../data/online_retail.csv')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [2]:
df.shape

(1067371, 8)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 65.1 MB

In [4]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(34335)

In [6]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [7]:
df['Invoice'].str.startswith('C').sum()

np.int64(19494)

In [8]:
df[df['Price'] <= 0].shape

(6207, 8)

In [9]:
df.copy()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [10]:
df_clean = df.copy()
df_clean.shape

(1067371, 8)

In [11]:
df_clean.drop_duplicates(inplace=True)

In [12]:
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])

In [13]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 1033036 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1033036 non-null  str
 1   StockCode    1033036 non-null  str
 2   Description  1028761 non-null  str
 3   Quantity     1033036 non-null  int64
 4   InvoiceDate  1033036 non-null  datetime64[us]
 5   Price        1033036 non-null  float64
 6   Customer ID  797885 non-null   float64
 7   Country      1033036 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 70.9 MB

In [14]:
returns = df_clean[df_clean['Invoice'].str.startswith('C')]
returns.shape

(19104, 8)

In [15]:
df_clean = df_clean[~df_clean['Invoice'].str.startswith('C')]
df_clean.shape

(1013932, 8)

In [16]:
df_clean = df_clean[df_clean['Price'] > 0]
df_clean.shape

(1007913, 8)

In [17]:
df_clean['Revenue'] = df_clean['Price'] * df_clean['Quantity']
df_clean.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [18]:
df_clean = df_clean[ ~ df_clean['Quantity'].isin([ 80995, 74215 ]) ]
df_clean.shape

(1007911, 9)

In [21]:
non_product_codes = ['POST', 'DOT', 'M', 'm', 'C2', 'D', 'S', 'B']
non_products = df_clean[df_clean['StockCode'].isin(non_product_codes)]
df_clean = df_clean[~df_clean['StockCode'].isin(non_product_codes)]
print(non_products.shape, df_clean.shape)

(4393, 9) (1003518, 9)

In [22]:
df_clean[df_clean['StockCode'].str.len() >= 8][['StockCode', 'Description']].drop_duplicates()

           StockCode                         Description
2377        DCGS0058                    MISO PRETTY  GUM
2378        DCGS0068                   DOGS NIGHT COLLAR
8371        DCGS0004          HAYNES CAMPER SHOULDER BAG
8373        DCGS0076        SUNJAR LED NIGHT NIGHT LIGHT
18466   BANK CHARGES                        Bank Charges
20249       DCGS0003                 BOXED GLASS ASHTRAY
30672       DCGS0072              CAT CAMOUFLAGUE COLLAR
31079   gift_0001_80  Dotcomgiftshop Gift Voucher £80.00
32048   gift_0001_20  Dotcomgiftshop Gift Voucher £20.00
33819       DCGS0044             HANDZ-OFF CAR FRESHENER
40904   gift_0001_10  Dotcomgiftshop Gift Voucher £10.00
41263   gift_0001_50  Dotcomgiftshop Gift Voucher £50.00
44245      DCGS0066N             NAVY CUDDLES DOG HOODIE
45212   gift_0001_30  Dotcomgiftshop Gift Voucher £30.00
123592      DCGS0069               OOH LA LA DOGS COLLAR
148098  BANK CHARGES                        Bank Charges
148842      DCGS0070               CAMOUFLAGE DOG COLLAR
148843      DCGS0075                CAMOUFLAGUE DOG LEAD
222345      DCGS0041    HAYNES MINI-COOPER PLAYING CARDS
235291  gift_0001_70  Dotcomgiftshop Gift Voucher £70.00
236545      DCGS0037                  KEY-RING CORKSCREW
244830      DCGSSBOY                      BOYS PARTY BAG
244831     DCGSSGIRL                     GIRLS PARTY BAG
299652  gift_0001_40  Dotcomgiftshop Gift Voucher £40.00
414064      DCGS0062             ROAD-RAGE CAR FRESHENER
440698     AMAZONFEE                          AMAZON FEE

In [26]:
extra = (df_clean['StockCode'].isin(['BANK CHARGES', 'AMAZONFEE']) | df_clean['StockCode'].str.startswith('gift_', na=False)).astype(bool)
non_products = pd.concat([non_products, df_clean[extra]])
df_clean = df_clean[~extra]
print(non_products.shape, df_clean.shape)

(4507, 9) (1003404, 9)

In [27]:
df_clean.to_csv('../data/clean_sales.csv', index=False)

In [28]:
returns.to_csv('../data/returns.csv', index=False)

In [29]:
non_products.to_csv('../data/non_products.csv', index=False)